### ISSUE TITLE
elementQuery method is failing when used with browser.execute

### ISSUE THREAD

**Issue by soduor** [jambit/wdio-cucumber-selected-steps#16]
Description: When I use the elementQuery as a parameter with browser.execute method an error is thrown. 
browser.execute("arguments[0].play();",elementQuery('video'));

Error:
Malformed type for "args" parameter of command executeScript
Expected: (string|object|number|boolean|undefined)[]
Actual: (function)[]

Workaround: Use WebdriverIO $() method instead
browser.execute("arguments[0].play();", $('video'));

Steps to reproduce:
git clone https://github.com/soduor/wdio-cucumber-selected-steps-demo.git
yarn install
yarn bug
Notice the test fails

Files: 
src/selectors/playVideo.js
src/features/playVideo.feature
src/steps/playVideo.ts
src/support/playVideo.ts

**Comment by SantoJambit** [comment]
Hi @soduor,

sorry for the delay. The time after new year is usually especially busy.

elementQuery returns you a function, not an element by itself. You'll still need to call that function.
I.e., the correct way for your statement would be:

```typescript
browser.execute("arguments[0].play();",elementQuery('video')());
```

I know this syntax looks a bit confusing. The reason elementQuery returns a function is as follows:
If you where to query the element once and it does not exist, you can't easily wait for its existence without calling elementQuery over and over again. The return value of elementQuery is more like a "how to find an element", rather than the element itself (otherwise I would have named it `find/queryElement`).

I hope this clears it up.

**Comment by soduor** [comment]
Thanks. It works!
